FASTP:
  THREADS: 4
  MIN_LENGTH: 50
  QUALITY_THRESHOLD: 20
  WINDOW_SIZE: 4

SNIPPY:
  THREADS: 4
  MIN_DEPTH: 10
  FRAC_SUPP: 0.9
  MIN_QUALITY: 25
  MAP_QUALITY: 30

SPADES:
  THREADS: 4
  MEMORY: 4
  KMER_LENGTHS: "21,33,43,53,63"